/**
 * GENERATED by scripts/split-character-sheet.mjs — do not edit by hand.
 * available=false → the site draws ZUN with the code-defined SVG sprite.
 * Run `npm run character:split` after adding public/character/zun-sheet.png.
 */
export const characterManifest = {
  available: false,
  cells: {} as Record<string, { w: number; h: number }>,
} as const;
